// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Folder } from "./Folder";

export interface Backup { client_folder: Folder, server_folder: Folder, latest_run: bigint | null, }