// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Location } from "./Location";
import type { Options } from "./Options";

export interface Backup { client_location: Location, server_location: Location, latest_run: bigint | null, options: Options | null, }