// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Config { client_name: string, username: string, server_address: string, server_port: number, allow_background_backup: boolean, }