// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Backup } from "./Backup";

export interface Config { username: string, server_address: string, server_port: number, backups: Array<Backup>, }