// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { File } from "./File";
import type { Folder } from "./Folder";

export type Entity = { Folder: Folder } | { File: File };