// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Size } from "./Size";

export interface Folder { name: string, path: string, size: Size | null, }