name: CLI - Publish

permissions:
  contents: write

on:
  push:
    tags:
      - v[0-9]+.*-cli

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set version number variable
        id: set-version
        run: |
          # Extract the version number from the tag and strip "-cli" suffix
          CLI_VERSION="${GITHUB_REF#refs/tags/v}"
          CLI_VERSION="${CLI_VERSION%-cli}"
          echo "Version: $CLI_VERSION"
          echo "CLI_VERSION=$CLI_VERSION" >> "$GITHUB_OUTPUT"
      - name: Create release
        uses: taiki-e/create-gh-release-action@v1
        with:
          draft: true
          title: CLI v${{ steps.set-version.outputs.CLI_VERSION }}
          token: ${{ secrets.GITHUB_TOKEN }}

  upload-assets:
    needs: create-release
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        include:
          - os: ubuntu-latest
            features: systemd,io_uring
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install dependencies
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
               echo "Installing dependencies for $RUNNER_OS"
               sudo apt install libwebkit2gtk-4.0-dev build-essential curl wget file libssl-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev
          elif [ "$RUNNER_OS" == "macOS" ]; then
               echo "$RUNNER_OS has does not need to install any dependencies"
          else
               echo "$RUNNER_OS not supported"
               exit 1
          fi
      - uses: actions/checkout@v4
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: bmu
          manifest_path: src-tauri/Cargo.toml
          token: ${{ secrets.GITHUB_TOKEN }}
